name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project # 1. 只 checkout 主项目
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 注意：这里我们移除了 submodules: 'recursive'

      - name: Fix Submodule URL # 2. 强行修正错误的 URL
        run: |
          git config -f .gitmodules submodule.xwalk_core_library.url https://github.com/CatVodOpen/xwalk_core_library.git

      - name: Init Submodules # 3. 手动拉取所有子模块
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          packages: "cmdline-tools;latest platform-tools build-tools;34.0.0 platforms;android-34"

      - name: Build with Gradle
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m"
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache --parallel --no-daemon --warning-mode all

      - name: Collect APKs
        run: |
          mkdir -p "${{ github.workspace }}/apk"
          find app/build/outputs/apk -type f -name "*.apk" -exec cp {} "${{ github.workspace }}/apk/" \;

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: tvbox-apks
          path: ${{ github.workspace }}/apk
          if-no-files-found: error
