name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            build-tools;34.0.0
            platforms;android-34

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache --parallel --no-daemon --warning-mode all

      - name: Collect APKs
        run: |
          mkdir -p "${{ github.workspace }}/apk"
          find app/build/outputs/apk -type f -name "*.apk" -exec cp {} "${{ github.workspace }}/apk/" \;

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: tvbox-apks
          path: ${{ github.workspace }}/apk
          if-no-files-found: erro
